# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='peer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\npeer.proto\"\x1a\n\x0cGetSuccessor\x12\n\n\x02id\x18\x01 \x01(\t\"=\n\tSuccessor\x12\x0e\n\x06suc_id\x18\x01 \x01(\t\x12\x0e\n\x06suc_ip\x18\x02 \x01(\x0c\x12\x10\n\x08suc_port\x18\x03 \x01(\r23\n\x04Peer\x12+\n\x0cgetSuccessor\x12\r.GetSuccessor\x1a\n.Successor\"\x00\x62\x06proto3'
)




_GETSUCCESSOR = _descriptor.Descriptor(
  name='GetSuccessor',
  full_name='GetSuccessor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GetSuccessor.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=40,
)


_SUCCESSOR = _descriptor.Descriptor(
  name='Successor',
  full_name='Successor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='suc_id', full_name='Successor.suc_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='suc_ip', full_name='Successor.suc_ip', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='suc_port', full_name='Successor.suc_port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['GetSuccessor'] = _GETSUCCESSOR
DESCRIPTOR.message_types_by_name['Successor'] = _SUCCESSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetSuccessor = _reflection.GeneratedProtocolMessageType('GetSuccessor', (_message.Message,), {
  'DESCRIPTOR' : _GETSUCCESSOR,
  '__module__' : 'peer_pb2'
  # @@protoc_insertion_point(class_scope:GetSuccessor)
  })
_sym_db.RegisterMessage(GetSuccessor)

Successor = _reflection.GeneratedProtocolMessageType('Successor', (_message.Message,), {
  'DESCRIPTOR' : _SUCCESSOR,
  '__module__' : 'peer_pb2'
  # @@protoc_insertion_point(class_scope:Successor)
  })
_sym_db.RegisterMessage(Successor)



_PEER = _descriptor.ServiceDescriptor(
  name='Peer',
  full_name='Peer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=105,
  serialized_end=156,
  methods=[
  _descriptor.MethodDescriptor(
    name='getSuccessor',
    full_name='Peer.getSuccessor',
    index=0,
    containing_service=None,
    input_type=_GETSUCCESSOR,
    output_type=_SUCCESSOR,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PEER)

DESCRIPTOR.services_by_name['Peer'] = _PEER

# @@protoc_insertion_point(module_scope)
