# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import peer_pb2 as peer__pb2


class PeerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getSuccessor = channel.unary_unary(
                '/Peer/getSuccessor',
                request_serializer=peer__pb2.GetSuccessor.SerializeToString,
                response_deserializer=peer__pb2.Successor.FromString,
                )


class PeerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getSuccessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getSuccessor': grpc.unary_unary_rpc_method_handler(
                    servicer.getSuccessor,
                    request_deserializer=peer__pb2.GetSuccessor.FromString,
                    response_serializer=peer__pb2.Successor.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Peer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Peer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getSuccessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Peer/getSuccessor',
            peer__pb2.GetSuccessor.SerializeToString,
            peer__pb2.Successor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
